import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Starting Banaras Darshan seed...");

  // Clean existing data
  await prisma.savedPlace.deleteMany({});
  await prisma.report.deleteMany({});
  await prisma.communityReply.deleteMany({});
  await prisma.communityMessage.deleteMany({});
  await prisma.moderationLog.deleteMany({});
  await prisma.trip.deleteMany({});
  await prisma.feedback.deleteMany({});
  await prisma.placeSuggestion.deleteMany({});
  await prisma.place.deleteMany({});
  await prisma.user.deleteMany({});

  // Seed Users
  const adminUser = await prisma.user.create({
    data: {
      id: "usr_admin",
      name: "Banaras Darshan Editorial",
      email: "team@banarasdarshan.com",
      role: "ADMIN",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80",
      bio: "Official curation and heritage verification team of Banaras Darshan.",
      badge: "Verified Contributor",
      reputation: 990,
    },
  });

  const localGuide = await prisma.user.create({
    data: {
      id: "usr_panditji",
      name: "Pt. Rameshwar Shastri",
      email: "rameshwar@kashiguide.in",
      role: "MODERATOR",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80",
      bio: "8th generation Kashi resident, Sanskrit scholar and Vedic heritage researcher.",
      badge: "Local Guide",
      reputation: 450,
    },
  });

  const travelerUser = await prisma.user.create({
    data: {
      id: "usr_traveler_ananya",
      name: "Ananya Sharma",
      email: "ananya.travels@gmail.com",
      role: "USER",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=256&q=80",
      bio: "Solo female backpacker exploring heritage corridors and street food across India.",
      badge: "Helpful Traveler",
      reputation: 180,
    },
  });

  console.log("✓ Created 3 users with reputation and roles");

  // Seed Places
  const placesData = [
    // --- TEMPLES ---
    {
      slug: "kashi-vishwanath-temple",
      name: "Shri Kashi Vishwanath Temple",
      hindiName: "श्री काशी विश्वनाथ मंदिर",
      category: "TEMPLE",
      subCategory: "Jyotirlinga & Golden Temple",
      tagline: "The spiritual heart of Kashi and one of the twelve sacred Jyotirlingas.",
      description: "Rebuilt grandly under the Kashi Vishwanath Corridor project connecting directly to the Ganga at Lalita Ghat. The gold-plated spire was donated by Maharaja Ranjit Singh in 1835. The temple is dedicated to Lord Shiva, the presiding cosmic deity of Varanasi.",
      history: "Ancient shrine mentioned in the Skanda Purana. Reconstructed in 1780 by Queen Ahilyabai Holkar of Indore, and modernized in 2021 with a spacious riverfront corridor.",
      address: "Lahori Tola, Varanasi, Uttar Pradesh 221001",
      area: "Godowlia / Lalita Ghat",
      latitude: 25.3109,
      longitude: 83.0107,
      image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=80",
      rating: 4.9,
      reviewCount: 3840,
      approxBudget: "Free (Special VIP pass available online)",
      budgetTier: "FREE",
      bestTimeToVisit: "4:00 AM (Mangala Aarti) or 8:30 PM (Shringar Aarti)",
      openingHours: "03:00 AM – 11:00 PM (Temple doors close briefly between aartis)",
      visitingTips: "Mobile phones, leather belts, electronic items, and large bags are strictly prohibited inside the sanctum. Free digital lockers are provided at Corridor Gate 4.",
      safetyNotes: "Expect heavy queues on Mondays and during Sawan/Shivratri. Book Sugam Darshan online on the official trust portal to avoid touts.",
      isVerified: true,
      isFeatured: true,
      isHiddenGem: false,
      tags: "Jyotirlinga,Spiritual,Ahilyabai Holkar,Ganga Corridor,Lord Shiva",
      nearestHub: "Varanasi Cantt Station: 4.5 km | Godowlia Chauraha: 400m",
    },
    {
      slug: "sankat-mochan-hanuman-temple",
      name: "Sankat Mochan Hanuman Temple",
      hindiName: "संकट मोचन हनुमान मंदिर",
      category: "TEMPLE",
      subCategory: "Historic Hanuman Shrine",
      tagline: "Founded by Goswami Tulsidas, renowned for its peaceful energy and sacred Besan Ladoo prasad.",
      description: "Situated on the banks of the Assi river stream, this revered shrine was founded by saint-poet Goswami Tulsidas who composed the Ramcharitmanas and Hanuman Chalisa. Lord Hanuman stands facing Lord Rama.",
      history: "Believed to mark the spot where Tulsidas had a divine vision of Hanuman in the 16th century. It hosts the prestigious annual Sankat Mochan Sangeet Samaroh.",
      address: "Sankat Mochan Road, Saket Nagar, Nagwa, Varanasi 221005",
      area: "Assi / Lanka",
      latitude: 25.2816,
      longitude: 82.9984,
      image: "https://images.unsplash.com/photo-1609342122563-a43ac8917a3a?auto=format&fit=crop&w=1200&q=80",
      rating: 4.8,
      reviewCount: 1920,
      approxBudget: "Free",
      budgetTier: "FREE",
      bestTimeToVisit: "Tuesday or Saturday early morning (6:00 AM) or evening 7:30 PM Aarti",
      openingHours: "05:00 AM – 12:00 PM, 04:00 PM – 10:00 PM",
      visitingTips: "Try the iconic pure ghee Besan Ladoo from the internal temple counter. Mind the friendly resident monkeys; keep food packets tucked away.",
      safetyNotes: "Metal detectors at entry. No photography allowed in sanctum.",
      isVerified: true,
      isFeatured: true,
      isHiddenGem: false,
      tags: "Hanuman,Tulsidas,Assi,Spiritual,Music Festival",
      nearestHub: "Assi Ghat: 1.6 km | BHU Main Gate: 1.2 km",
    },
    {
      slug: "kaal-bhairav-temple",
      name: "Kaal Bhairav Temple",
      hindiName: "काल भैरव मंदिर",
      category: "TEMPLE",
      subCategory: "Guardian of Kashi",
      tagline: "The Kotwal (Chief Police Officer) of Varanasi; guardian deity whose darshan is essential.",
      description: "Kaal Bhairav is the fierce manifestation of Shiva serving as the supreme protector of the city. According to tradition, anyone visiting or residing in Kashi must seek Bhairav Baba's permission and blessing.",
      history: "One of the oldest surviving Shiva temples in Varanasi, venerated for centuries by tantriks, pilgrims, and city guardians alike.",
      address: "Bhaironath, Vishweshwarganj, Varanasi 221001",
      area: "Chowk / Maidagin",
      latitude: 25.3182,
      longitude: 83.0135,
      image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
      rating: 4.7,
      reviewCount: 1450,
      approxBudget: "Free (Mustard oil lamps: ₹20-50)",
      budgetTier: "FREE",
      bestTimeToVisit: "Sunday mornings or mid-afternoons to avoid long narrow lane queues",
      openingHours: "05:00 AM – 01:30 PM, 04:30 PM – 09:30 PM",
      visitingTips: "Tie a black consecrated sacred thread (Kashi Kalawa) on your wrist from the priest. Priests perform mild symbolic peacock-feather blessings.",
      safetyNotes: "The lanes approaching Bhaironath are very narrow. Walk or take an e-rickshaw up to Maidagin Chauraha.",
      isVerified: true,
      isFeatured: false,
      isHiddenGem: false,
      tags: "Kotwal,Protector,Bhaironath,Shiva,Spiritual",
      nearestHub: "Maidagin Chauraha: 300m | Chowk: 600m",
    },
    {
      slug: "durga-kund-temple",
      name: "Durga Kund Mandir",
      hindiName: "दुर्गा कुंड मंदिर",
      category: "TEMPLE",
      subCategory: "Nagara Style Heritage Temple",
      tagline: "Vibrant red 18th-century temple dedicated to Goddess Durga, featuring a sacred water tank.",
      description: "Built in multi-tiered North Indian Nagara architecture with ocher red stucco, this powerful Shakti shrine stands beside the historic rectangular Durga Kund water reservoir. It is also historically nicknamed the Monkey Temple by early European travelers.",
      history: "Commissioned in the 18th century by Rani Bhabani of Natore (Bengal). The idol of Goddess Durga is believed to be swayambhu (self-manifested).",
      address: "Durga Kund Road, Durgakund, Jawahar Nagar, Varanasi 221005",
      area: "Durga Kund",
      latitude: 25.2891,
      longitude: 82.9997,
      image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
      rating: 4.7,
      reviewCount: 980,
      approxBudget: "Free",
      budgetTier: "FREE",
      bestTimeToVisit: "Navratri festival or Tuesdays and Fridays during evening sandhya aarti",
      openingHours: "05:00 AM – 11:00 PM",
      visitingTips: "Visit the nearby famous Anand Mayee Ashram and Tulsi Manas Mandir which are within walking distance.",
      safetyNotes: "Keep eye contact minimal with monkeys on the outer perimeter walls.",
      isVerified: true,
      isFeatured: false,
      isHiddenGem: false,
      tags: "Durga,Shakti,Rani Bhabani,Heritage Architecture",
      nearestHub: "Assi Ghat: 1.4 km | Sankat Mochan: 700m",
    },

    // --- GHATS ---
    {
      slug: "dashashwamedh-ghat",
      name: "Dashashwamedh Ghat",
      hindiName: "दशाश्वमेध घाट",
      category: "GHAT",
      subCategory: "Grand Ganga Aarti Hub",
      tagline: "The most vibrant, historic, and spectacular ghat of Varanasi where the world watches the Ganga Aarti.",
      description: "Dashashwamedh is the life pulse of Kashi. Every evening at sunset, seven young priests perform the synchronized Maha Aarti holding multi-tiered brass oil lamps, conch shells, and incense before thousands of devotees seated on ghat steps and wooden river boats.",
      history: "According to legend, Lord Brahma performed the Dasa-Ashwamedha (ten-horse sacrifice) here for King Divodasa. Peshwa Balaji Baji Rao renovated it in 1740, and Queen Ahilyabai Holkar added extensions.",
      address: "Dashashwamedh Ghat Road, Godowlia, Varanasi 221001",
      area: "Godowlia / Dashashwamedh",
      latitude: 25.3075,
      longitude: 83.0105,
      image: "https://images.unsplash.com/photo-1571536802807-30451e3955d8?auto=format&fit=crop&w=1200&q=80",
      rating: 4.9,
      reviewCount: 5200,
      approxBudget: "Free | Boat ride: ₹150 - ₹350 per seat",
      budgetTier: "FREE",
      bestTimeToVisit: "Sunset (5:45 PM – 7:30 PM) for the Ganga Aarti or 5:30 AM for dawn boat rides",
      openingHours: "Open 24 hours (Ganga Aarti begins around 6:30 PM in summer / 6:00 PM in winter)",
      visitingTips: "Arrive by 5:30 PM to get front-row step seating, or hire a shared boat to watch the Aarti illuminated from the river.",
      safetyNotes: "Watch personal belongings in crowds. Do not pay boatmen before boarding; negotiate government-approved slab rates.",
      isVerified: true,
      isFeatured: true,
      isHiddenGem: false,
      tags: "Ganga Aarti,Iconic,Boat Ride,Evening Ritual,Sunrise",
      nearestHub: "Godowlia Crossing: 300m | Cantt Station: 4.8 km",
    },
    {
      slug: "assi-ghat",
      name: "Assi Ghat",
      hindiName: "अस्सी घाट",
      category: "GHAT",
      subCategory: "Subah-e-Banaras & Cultural Confluence",
      tagline: "Varanasi's cultural sanctuary for sunrise meditation, Vedic chanting, yoga, and riverfront cafes.",
      description: "Located at the holy sangam of the Ganga and the Assi river stream. Assi is celebrated for 'Subah-e-Banaras', a daily dawn cultural tradition featuring Vedic havan, musical ragas, and community yoga as the golden sun rises over the eastern bank.",
      history: "Associated with Goddess Durga laying down her sword (Asi) after defeating demons Shumbha and Nishumbha. Mentioned in the Kurma Purana and Matsya Purana.",
      address: "Assi Road, Anandbagh, Bhelupur, Varanasi 221005",
      area: "Assi",
      latitude: 25.2894,
      longitude: 83.0068,
      image: "https://images.unsplash.com/photo-1598091383021-15ddea10925d?auto=format&fit=crop&w=1200&q=80",
      rating: 4.9,
      reviewCount: 3400,
      approxBudget: "Free | Morning boat: ₹100 - ₹200",
      budgetTier: "FREE",
      bestTimeToVisit: "Sunrise (5:00 AM – 7:00 AM) for Subah-e-Banaras and quiet chai",
      openingHours: "Open 24 hours",
      visitingTips: "After the morning aarti, grab lemon tea or kullad chai and fresh jalebis at the ghat steps. Pizzeria Vaatika Cafe is just steps away.",
      safetyNotes: "Safe and traveler-friendly even early morning. Avoid stepping onto slippery algae-covered lower stone steps.",
      isVerified: true,
      isFeatured: true,
      isHiddenGem: false,
      tags: "Subah-e-Banaras,Sunrise,Yoga,Vedic Chanting,Cafes",
      nearestHub: "BHU Campus: 1.5 km | Lanka: 1 km",
    },
    {
      slug: "manikarnika-ghat",
      name: "Manikarnika Ghat",
      hindiName: "मणिकर्णिका घाट",
      category: "GHAT",
      subCategory: "The Eternal Mahashmashan",
      tagline: "The sacred cremation ghat where the flame has never extinguished for thousands of years.",
      description: "Known as the Great Cremation Ground (Mahashmashan). In Hindu philosophy, dying or being cremated in Kashi grants Moksha (liberation from the cycle of rebirth). The eternal fire tended by the Dom Raja community has burned continuously across millennia.",
      history: "Mythologically connected to Lord Shiva's earring (Manikarnika) falling into the holy well dug by Lord Vishnu, known as Manikarnika Kund.",
      address: "Manikarnika Ghat, Chowk, Varanasi 221001",
      area: "Chowk / Lahori Tola",
      latitude: 25.3106,
      longitude: 83.0139,
      image: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1200&q=80",
      rating: 4.8,
      reviewCount: 2150,
      approxBudget: "Free",
      budgetTier: "FREE",
      bestTimeToVisit: "Daytime or from a distance via boat; approach with quiet reverence",
      openingHours: "Open 24 hours",
      visitingTips: "Strictly observe solemnity and respect. Dress conservatively. Observe from the upper walkways or from a passing boat.",
      safetyNotes: "CRITICAL: Photography and video recording of cremation pyres are STRICTLY FORBIDDEN. Beware of scam touts asking for 'cremation wood donation' money.",
      isVerified: true,
      isFeatured: false,
      isHiddenGem: false,
      tags: "Moksha,Sacred,Eternal Fire,Spiritual Philosophy,Heritage",
      nearestHub: "Kashi Vishwanath Corridor: 200m | Chowk: 500m",
    },
    {
      slug: "chet-singh-ghat",
      name: "Chet Singh Ghat",
      hindiName: "चेत सिंह घाट",
      category: "GHAT",
      subCategory: "Fortress Ghat of Historical Valor",
      tagline: "Imposing fortress architecture with grand stone bastions on the riverfront.",
      description: "Resembling a majestic medieval fortress rising directly from the river, Chet Singh Ghat was the fortified palace of Maharaja Chet Singh of Banaras who rebelled and defeated the British East India Company troops led by Warren Hastings in 1781.",
      history: "Site of the historic 1781 clash where Chet Singh's soldiers surrounded Warren Hastings, who famously fled disguised as a woman, giving rise to the local folk saying.",
      address: "Chet Singh Ghat, Shivala, Varanasi 221001",
      area: "Shivala",
      latitude: 25.2974,
      longitude: 83.0076,
      image: "https://images.unsplash.com/photo-1590766940554-634a7ed41450?auto=format&fit=crop&w=1200&q=80",
      rating: 4.7,
      reviewCount: 890,
      approxBudget: "Free",
      budgetTier: "FREE",
      bestTimeToVisit: "Late afternoon for cinematic photographs of stone battlements",
      openingHours: "Open 24 hours",
      visitingTips: "Great quiet spot away from the heavy crowds of Dashashwamedh. Excellent background for architectural photography.",
      safetyNotes: "Stone steps can be steep. No swimming near deep embankment.",
      isVerified: true,
      isFeatured: false,
      isHiddenGem: true,
      tags: "Fortress,History,Warren Hastings,Architecture,Quiet",
      nearestHub: "Shivala Chauraha: 400m | Assi Ghat: 1 km",
    },

    // --- FOOD DISCOVERY ---
    {
      slug: "kashi-chaat-bhandar",
      name: "Kashi Chaat Bhandar",
      hindiName: "काशी चाट भण्डार",
      category: "FOOD",
      subCategory: "Legendary Banarasi Chaat",
      tagline: "Varanasi's most acclaimed chaat destination, world-famous for its piping hot Tamatar Chaat.",
      description: "Serving authentic Banarasi chaat since 1968. Their signature creation is Tamatar Chaat — mashed tomatoes slow-cooked in ghee with hing, cashews, and secret spices, served bubbling hot in an earthen kullad drizzled with sweet sugar syrup.",
      history: "Founded by Kashi Nath Keshari, this legendary shop has been featured by national and international food explorers for decades.",
      address: "D.57/59, Dashashwamedh Road, Girja Ghar Chauraha, Godowlia, Varanasi 221001",
      area: "Godowlia",
      latitude: 25.3092,
      longitude: 83.0072,
      image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=80",
      rating: 4.9,
      reviewCount: 4200,
      approxBudget: "₹100 - ₹200 per person",
      budgetTier: "BUDGET",
      bestTimeToVisit: "4:30 PM (just as fresh evening batches start) to beat the dinner peak",
      openingHours: "04:00 PM – 10:30 PM (Closed early if stock finishes)",
      visitingTips: "Must-try items: Tamatar Chaat, Palak Patta Chaat, Dahi Katori Chaat, and Gulab Jamun.",
      safetyNotes: "100% vegetarian, hygienic filtered water used. Expect a 10-15 minute wait during peak evening hours.",
      isVerified: true,
      isFeatured: true,
      isHiddenGem: false,
      tags: "Tamatar Chaat,Street Food,Vegetarian,Famous,Must-Try",
      popularDishes: "Tamatar Chaat, Palak Patta Chaat, Dahi Golgappe, Gulab Jamun",
      isPureVeg: true,
      nearestHub: "Girja Ghar Chauraha: 50m | Dashashwamedh Ghat: 450m",
    },
    {
      slug: "ram-bhandar-kachori",
      name: "Ram Bhandar",
      hindiName: "राम भण्डार",
      category: "FOOD",
      subCategory: "Iconic Banarasi Breakfast",
      tagline: "The golden standard of Banaras morning breakfast: desi ghee kachori, spicy chane ki sabzi, and fresh jalebi.",
      description: "Deep in the narrow lanes of Thatheri Bazaar, Ram Bhandar has been serving pure desi ghee kachori-sabzi every single morning for over a century. The kachori is stuffed with spiced urad dal and served on a dried sal leaf dona.",
      history: "Established in 1897, maintaining generational heritage recipes cooked on traditional brass karahis.",
      address: "CK 37/35, Thatheri Bazaar, Chowk, Varanasi 221001",
      area: "Chowk / Thatheri Bazaar",
      latitude: 25.3134,
      longitude: 83.0112,
      image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=1200&q=80",
      rating: 4.8,
      reviewCount: 2310,
      approxBudget: "₹60 - ₹120 per person",
      budgetTier: "BUDGET",
      bestTimeToVisit: "7:00 AM – 9:00 AM (Stock often sells out by 10:30 AM!)",
      openingHours: "06:30 AM – 11:00 AM only",
      visitingTips: "Order the Badi Kachori with Chana & Aloo Rasedaar sabzi, accompanied by hot thin-crisp saffron jalebis.",
      safetyNotes: "Only open in the morning. Located inside a walking-only lane, best reached on foot from Chowk.",
      isVerified: true,
      isFeatured: true,
      isHiddenGem: false,
      tags: "Kachori,Breakfast,Jalebi,Chowk,Desi Ghee",
      popularDishes: "Desi Ghee Badi Kachori, Sabzi, Choti Kachori, Crispy Jalebi",
      isPureVeg: true,
      nearestHub: "Chowk Thana: 250m | Kashi Vishwanath Gate 1: 400m",
    },
    {
      slug: "blue-lassi-shop",
      name: "Blue Lassi Shop",
      hindiName: "ब्लू लस्सी शॉप",
      category: "FOOD",
      subCategory: "Hand-Churned Clay Pot Lassi",
      tagline: "Famous heritage shop hand-churning thick artisan lassi with fresh seasonal fruits since 1925.",
      description: "A cozy hole-in-the-wall spot famous among travelers worldwide. Their lassi is whipped with a wooden churner (madhani) in earthenware bowls and garnished with rabdi, malai, pistachios, almonds, and fruits like pomegranate, mango, or banana.",
      history: "Founded in 1925 by the Yadav family. Its blue-painted walls are covered in thousands of passport photos and handwritten notes left by travelers across 90+ countries.",
      address: "CK 12/1, Kunj Gali, near Manikarnika Ghat, Chowk, Varanasi 221001",
      area: "Chowk / Manikarnika Lane",
      latitude: 25.3115,
      longitude: 83.0128,
      image: "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?auto=format&fit=crop&w=1200&q=80",
      rating: 4.8,
      reviewCount: 3100,
      approxBudget: "₹80 - ₹150 per kullad",
      budgetTier: "BUDGET",
      bestTimeToVisit: "11:00 AM – 4:00 PM for afternoon refreshment",
      openingHours: "08:00 AM – 10:30 PM",
      visitingTips: "Try the Rabdi-Pomegranate Lassi or Banana-Coconut Lassi. Bring a stamp-size photo to pin on their traveler wall.",
      safetyNotes: "Pure curd and dairy used. Lane is pedestrian only.",
      isVerified: true,
      isFeatured: true,
      isHiddenGem: false,
      tags: "Lassi,Rabdi,Clay Pot,Heritage,Traveler Wall",
      popularDishes: "Dry Fruit Special Lassi, Pomegranate Rabdi Lassi, Mango Lassi",
      isPureVeg: true,
      nearestHub: "Manikarnika Ghat: 150m | Chowk: 350m",
    },
    {
      slug: "keshav-tambool-bhandar",
      name: "Keshav Tambool Bhandar",
      hindiName: "केशव ताम्बूल भण्डार",
      category: "FOOD",
      subCategory: "Authentic Banarasi Paan",
      tagline: "The gold standard of Banarasi Paan, where celebrities and connoisseurs savor the melting Magahi leaf.",
      description: "Banarasi Paan is protected with a Geographical Indication (GI) tag. Keshav Tambool serves pure Magahi and Desi Paan leaves stuffed with gulkand, natural rose water, saffron paste, edible silver foil (varq), and aromatic digestives without tobacco.",
      history: "Operated by the Chaurasia family for multiple generations, celebrated as a cultural institution of Kashi.",
      address: "Assi Crossing, near Assi Ghat Road, Nagwa, Varanasi 221005",
      area: "Assi",
      latitude: 25.2902,
      longitude: 83.0041,
      image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1200&q=80",
      rating: 4.9,
      reviewCount: 1850,
      approxBudget: "₹30 - ₹70 per paan",
      budgetTier: "BUDGET",
      bestTimeToVisit: "Post-dinner (8:00 PM – 10:30 PM)",
      openingHours: "07:00 AM – 11:30 PM",
      visitingTips: "Ask for 'Desi Meetha Paan without Supari' or 'Magahi Kashi Special'. It literally melts in the mouth within seconds.",
      safetyNotes: "100% tobacco-free traditional meetha paan options available.",
      isVerified: true,
      isFeatured: false,
      isHiddenGem: false,
      tags: "Banarasi Paan,GI Tag,Magahi Leaf,Digestive,Heritage",
      popularDishes: "Special Banarasi Meetha Paan, Magahi Paan, Navratan Paan",
      isPureVeg: true,
      nearestHub: "Assi Ghat: 200m",
    },
    {
      slug: "shreeji-sweets-malaiyo",
      name: "Shreeji Sweets & Milk (Malaiyo Special)",
      hindiName: "श्रीजी मिष्ठान भण्डार (मलइयो)",
      category: "FOOD",
      subCategory: "Winter Saffron Dewdrop Cloud Sweet",
      tagline: "Home of Banaras's magical culinary marvel: Malaiyo (raw milk foam infused with saffron and winter dew).",
      description: "Malaiyo is an ethereal sweet made only in winter (November to February). Raw milk is boiled with saffron and cardamom, placed under the open night sky to absorb winter dew, and vigorously hand-frothed in the morning into cloud-like, melt-in-mouth golden foam topped with chopped pistachios.",
      history: "Generations of milk halwais in Chowk have perfected this seasonal miracle, preserving it as an intangible culinary heritage of Varanasi.",
      address: "CK 33/17, Neelkanth, Chowk, Varanasi 221001",
      area: "Chowk / Neelkanth",
      latitude: 25.3121,
      longitude: 83.0118,
      image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=1200&q=80",
      rating: 4.9,
      reviewCount: 1600,
      approxBudget: "₹50 - ₹90 per clay bowl",
      budgetTier: "BUDGET",
      bestTimeToVisit: "Early mornings in winter (7:00 AM – 11:00 AM)",
      openingHours: "06:30 AM – 12:00 PM (Winter seasonal)",
      visitingTips: "Must be eaten with a tiny wooden spoon. As soon as it touches your tongue, the cloud vanishes into saffron sweetness.",
      safetyNotes: "Only available mid-November through February due to cold weather requirements.",
      isVerified: true,
      isFeatured: true,
      isHiddenGem: true,
      tags: "Malaiyo,Winter Sweet,Saffron,Milk Cloud,Unique",
      popularDishes: "Kesar Malaiyo, Pista Rabdi, Hot Kadai Milk with Saffron",
      isPureVeg: true,
      nearestHub: "Kashi Vishwanath Gate 2: 250m",
    },

    // --- HOTELS & STAYS ---
    {
      slug: "brijrama-palace",
      name: "BrijRama Palace Varanasi",
      hindiName: "बृजरामा पैलेस",
      category: "HOTEL",
      subCategory: "Heritage Luxury Palace on the Ganga",
      tagline: "One of the oldest stone palaces on the ghats (1812), accessible via royal heritage boat.",
      description: "Perched majestically above Darbhanga Ghat, BrijRama Palace is an architectural triumph built in 1812 by the Maharaja of Nagpur. Guests arrive by private wooden bajra boat and ascend via South Asia's first heritage elevator. Features traditional Maratha stone carving and live classical sitar evenings.",
      history: "Restored meticulously under the heritage hospitality banner while preserving ancient sandstone balconies and temple ramparts.",
      address: "Darbhanga Ghat, Dashashwamedh, Varanasi 221001",
      area: "Darbhanga Ghat / Dashashwamedh",
      latitude: 25.3054,
      longitude: 83.0112,
      image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
      rating: 4.9,
      reviewCount: 1250,
      approxBudget: "₹22,000 - ₹45,000 per night",
      budgetTier: "LUXURY",
      bestTimeToVisit: "October to March",
      openingHours: "Check-in: 2:00 PM | Check-out: 12:00 PM",
      visitingTips: "Non-guests can reserve a high tea or fine dining experience at the riverfront terrace restaurant.",
      safetyNotes: "Pure vegetarian property; alcohol is strictly not served out of sanctity for the holy river.",
      isVerified: true,
      isFeatured: true,
      isHiddenGem: false,
      tags: "Luxury,Heritage Palace,Ghat View,Boat Arrival,Classical Music",
      amenities: "Direct River View, Heritage Elevator, Classical Sitar Evenings, Free WiFi, Gourmet Dining, Boat Transfers",
      nearestHub: "Dashashwamedh Ghat: 200m | Cantt Station: 5 km",
    },
    {
      slug: "zostel-varanasi",
      name: "Zostel Varanasi",
      hindiName: "जोस्टल वाराणसी",
      category: "HOTEL",
      subCategory: "Backpacker Hostel & Community Hub",
      tagline: "Vibrant traveler hostel with cozy dorms, private rooms, rooftop cafe, and daily heritage walking tours.",
      description: "Located centrally within walking distance of Godowlia and Dashashwamedh Ghat, Zostel Varanasi is the social basecamp for solo travelers, digital nomads, and young explorers. Offers clean air-conditioned dorms, artistic murals, and organized boat excursions.",
      history: "A pioneer of organized backpacking culture in Varanasi, fostering cross-cultural conversations for over a decade.",
      address: "D 53/90 A, Luxa Road, near Ramakrishna Mission, Varanasi 221001",
      area: "Luxa / Godowlia",
      latitude: 25.3101,
      longitude: 83.0019,
      image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1200&q=80",
      rating: 4.7,
      reviewCount: 2850,
      approxBudget: "₹650 - ₹2,800 per night",
      budgetTier: "BUDGET",
      bestTimeToVisit: "Year-round",
      openingHours: "24/7 Front Desk",
      visitingTips: "Join their daily 6:00 AM sunrise boat tour and evening food walk led by resident trip managers.",
      safetyNotes: "CCTV surveillance, secure electronic keycard lockers, female-only dorms available.",
      isVerified: true,
      isFeatured: false,
      isHiddenGem: false,
      tags: "Hostel,Backpacker,Social,WiFi,Walking Tours,Budget",
      amenities: "AC Dorms, High Speed WiFi, Rooftop Cafe, Lockers, Laundry, Travel Desk",
      nearestHub: "Godowlia Chauraha: 600m | Cantt Station: 3.5 km",
    },
    {
      slug: "ganpati-guest-house",
      name: "Ganpati Guest House",
      hindiName: "गणपति गेस्ट हाउस",
      category: "HOTEL",
      subCategory: "Charming Courtyard Ghat Stay",
      tagline: "Famous colorful courtyard hotel with private river-facing balconies overlooking Meer Ghat.",
      description: "A traveler favorite for 25+ years, featuring brightly painted traditional frescoes in its sunny open-air courtyard. Rooms with balconies directly gaze over the Ganga, letting guests wake up to morning boat bells and river mist.",
      history: "Family-run heritage house situated right on the stone steps of Meer Ghat, moments from Kashi Vishwanath corridor.",
      address: "D 1/84, Meer Ghat, Dashashwamedh, Varanasi 221001",
      area: "Meer Ghat",
      latitude: 25.3088,
      longitude: 83.0125,
      image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80",
      rating: 4.6,
      reviewCount: 1650,
      approxBudget: "₹1,800 - ₹5,500 per night",
      budgetTier: "MID_RANGE",
      bestTimeToVisit: "September to April",
      openingHours: "Check-in: 1:00 PM | Check-out: 11:00 AM",
      visitingTips: "Request an upper floor river-view room for uninterrupted sunrise views over the Ganga.",
      safetyNotes: "Ghat location requires walking 300m through old stone lanes. Luggage porter assistance is available.",
      isVerified: true,
      isFeatured: false,
      isHiddenGem: true,
      tags: "Ghat View,Courtyard,Rooftop Restaurant,Quiet,Mid-Range",
      amenities: "Riverfront Balconies, Rooftop Restaurant, Free WiFi, Travel Guidance, Doctor on Call",
      nearestHub: "Dashashwamedh Ghat: 250m | Vishwanath Corridor Gate 4: 200m",
    },

    // --- HIDDEN BANARAS & GALLIYAN ---
    {
      slug: "vishwanath-gali-kachori-gali",
      name: "Vishwanath Gali & Kachori Gali",
      hindiName: "विश्वनाथ गली एवं कचौड़ी गली",
      category: "STREET",
      subCategory: "Historic Labyrinth & Silk Lane",
      tagline: "The living, breathing artery of ancient Varanasi where centuries of culture converge.",
      description: "Dating back over two millennia, these ultra-narrow ancient stone alleys are lined with historic shops selling pure brass puja utensils, sphatik lingams, genuine Varanasi rudraksha malas, fragrant attar, handloom silk scarves, and sizzling breakfast stalls.",
      history: "Connecting Godowlia to the inner sanctum of Kashi Vishwanath and Manikarnika Ghat, these gullies have witnessed pilgrims from Adi Shankaracharya to Mark Twain.",
      address: "Chowk to Godowlia stone corridor, Varanasi 221001",
      area: "Chowk / Vishwanath Corridor",
      latitude: 25.3116,
      longitude: 83.0102,
      image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=80",
      rating: 4.8,
      reviewCount: 2900,
      approxBudget: "Free to explore | Souvenirs: ₹100 - ₹1,500",
      budgetTier: "FREE",
      bestTimeToVisit: "Morning 8:00 AM for heritage architecture or 5:00 PM for market buzz",
      openingHours: "06:00 AM – 11:00 PM",
      visitingTips: "Wear comfortable walking shoes with good grip. Put your phone on wrist-strap mode and simply wander.",
      safetyNotes: "No motorized vehicles allowed. Mind sacred wandering cows who politely share the narrow corridor.",
      isVerified: true,
      isFeatured: true,
      isHiddenGem: false,
      tags: "Ancient Lanes,Shopping,Rudraksha,Attar,Heritage Walk",
      nearestHub: "Godowlia: 200m | Kashi Vishwanath Gate 1: 50m",
    },
    {
      slug: "sarai-mohana-weaver-colony",
      name: "Sarai Mohana Silk Weavers Colony",
      hindiName: "सराय मोहाना बुनकर बस्ती",
      category: "HIDDEN",
      subCategory: "GI-Tagged Handloom Silk Heritage",
      tagline: "The master artisans behind world-renowned Banarasi silk brocades and real zari sarees.",
      description: "A tranquil artisan village on the northern outskirts of Varanasi where entire families have practiced wooden pit-loom silk weaving for eight generations. Visitors can observe the hypnotic clatter of Jacquard cards weaving real gold and silver threads into Kadwa and Tanchoi patterns.",
      history: "Varanasi silk was praised in Buddhist Jataka tales and Mughal court chronicles. Today it holds the coveted Geographical Indication (GI) status.",
      address: "Sarai Mohana Village, near Rajghat, Varanasi 221007",
      area: "Rajghat / Northern Suburbs",
      latitude: 25.3345,
      longitude: 83.0421,
      image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1200&q=80",
      rating: 4.9,
      reviewCount: 780,
      approxBudget: "Free to visit | Direct loom sarees: ₹3,500 - ₹50,000+",
      budgetTier: "FREE",
      bestTimeToVisit: "10:00 AM – 4:00 PM on weekdays when looms are actively humming",
      openingHours: "09:30 AM – 06:00 PM",
      visitingTips: "Buying directly from the master weaver supports the artisan families directly without showroom middleman markups.",
      safetyNotes: "Take an auto-rickshaw or taxi to Rajghat and hire a local cycle rickshaw into the village lanes.",
      isVerified: true,
      isFeatured: false,
      isHiddenGem: true,
      tags: "Banarasi Silk,Handloom,Zari,Artisans,GI Tag,Offbeat",
      nearestHub: "Kashi Railway Station: 2.2 km | Rajghat: 1.5 km",
    },
    {
      slug: "lolark-kund",
      name: "Lolark Kund",
      hindiName: "लोलार्क कुंड",
      category: "HIDDEN",
      subCategory: "Ancient Underground Sun God Stepwell",
      tagline: "One of the oldest surviving 12-meter deep stone stepwells in Varanasi dedicated to Surya Dev.",
      description: "An extraordinary subterranean stepwell with steep stone staircases descending 50 feet into sacred reddish waters. Connected to ancient solar worship, it is believed to predate the Mahabharata era.",
      history: "Mentioned in the Kashi Khanda of the Skanda Purana. Dedicated to Lolark Aditya, one of the 12 sun deities protecting Kashi.",
      address: "Near Tulsi Ghat, Shivala, Varanasi 221005",
      area: "Shivala / Tulsi Ghat",
      latitude: 25.2925,
      longitude: 83.0071,
      image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
      rating: 4.7,
      reviewCount: 540,
      approxBudget: "Free",
      budgetTier: "FREE",
      bestTimeToVisit: "Morning hours (7:00 AM – 10:00 AM) for tranquil photography of geometric stone steps",
      openingHours: "06:00 AM – 06:00 PM",
      visitingTips: "The site is usually quiet except during the annual Lolark Chhath festival when thousands seek blessings.",
      safetyNotes: "Steps are steep; descend carefully with proper grip.",
      isVerified: true,
      isFeatured: false,
      isHiddenGem: true,
      tags: "Stepwell,Sun God,Ancient,Heritage Architecture,Quiet",
      nearestHub: "Tulsi Ghat: 150m | Assi Ghat: 600m",
    },
  ];

  for (const place of placesData) {
    await prisma.place.create({ data: place });
  }
  console.log(`✓ Seeded ${placesData.length} verified authentic Banaras places`);

  // Seed Community Messages with verified tags and reputation
  const msg1 = await prisma.communityMessage.create({
    data: {
      userId: localGuide.id,
      userName: localGuide.name,
      userBadge: localGuide.badge,
      userAvatar: localGuide.avatar,
      channel: "general",
      content: "Namaste fellow travelers! Pro tip for the evening Ganga Aarti at Dashashwamedh: The sunset timing has shifted to 6:20 PM this week. If you want a comfortable seat on the wooden bajra boats, arrive at Dashashwamedh Ghat by 5:45 PM. Shared boat seats are officially capped at ₹150–200 per person.",
      isVerified: true,
      verifiedNote: "Verified by Banaras Darshan Editorial: Ganga Aarti scheduled daily at 6:30 PM, boat fare regulations verified with River Police rate-card.",
      status: "APPROVED",
      helpfulCount: 34,
      createdAt: new Date(Date.now() - 3600 * 1000 * 4), // 4 hrs ago
    },
  });

  const msg2 = await prisma.communityMessage.create({
    data: {
      userId: travelerUser.id,
      userName: travelerUser.name,
      userBadge: travelerUser.badge,
      userAvatar: travelerUser.avatar,
      channel: "food",
      content: "Just tried the Tamatar Chaat at Kashi Chaat Bhandar near Girja Ghar chauraha and my mind is blown! The hing and desi ghee aroma with the sweet syrup on top sounds unusual but tastes celestial. Get the Palak Patta chaat as well. Total bill was ₹140 for both.",
      isVerified: true,
      verifiedNote: "Verified listing: Kashi Chaat Bhandar is open 4:00 PM - 10:30 PM, average cost ₹100-150.",
      status: "APPROVED",
      helpfulCount: 22,
      createdAt: new Date(Date.now() - 3600 * 1000 * 12),
    },
  });

  const msg3 = await prisma.communityMessage.create({
    data: {
      userId: "usr_backpacker_tom",
      userName: "Thomas Miller",
      userBadge: "New Explorer",
      channel: "help",
      content: "Hi everyone! I just arrived at Varanasi Cantt Railway Station (VBS). What is the standard auto-rickshaw fare to Godowlia / Dashashwamedh Ghat? Drivers outside are quoting ₹350.",
      isVerified: false,
      status: "APPROVED",
      helpfulCount: 8,
      createdAt: new Date(Date.now() - 3600 * 1000 * 2),
    },
  });

  // Reply to msg3
  await prisma.communityReply.create({
    data: {
      messageId: msg3.id,
      userId: localGuide.id,
      userName: localGuide.name,
      userBadge: localGuide.badge,
      content: "Do not pay ₹350! A shared E-rickshaw or Auto from Cantt station to Godowlia is only ₹30 per person. If you want a private reserved Auto, the fair rate is ₹120–150. You can also book an Uber Auto directly from the platform exit for an upfront fare.",
      isVerified: true,
      status: "APPROVED",
    },
  });

  console.log("✓ Seeded real-time community chat messages & verified replies");

  // Seed Trip Itinerary Example
  await prisma.trip.create({
    data: {
      userId: adminUser.id,
      title: "Classic 3-Day Heritage & Soul of Kashi",
      durationDays: 3,
      budgetTier: "BUDGET",
      travelStyle: "Spiritual + Food + Heritage",
      groupType: "Solo / Couple",
      itineraryJson: JSON.stringify([
        {
          day: 1,
          title: "The Awakening of Kashi: Dawn to Aarti",
          theme: "Riverfront immersion, dawn spiritual chanting, and the great Maha Aarti",
          activities: [
            {
              time: "05:00 AM",
              title: "Subah-e-Banaras at Assi Ghat",
              desc: "Experience morning Vedic chanting, classical morning ragas, and join local yoga on the ghat steps.",
              placeSlug: "assi-ghat",
              approxCost: "Free",
            },
            {
              time: "07:30 AM",
              title: "Breakfast at Ram Bhandar",
              desc: "Desi ghee kachori-sabzi with hot crispy jalebis in the ancient Thatheri Bazaar lane.",
              placeSlug: "ram-bhandar-kachori",
              approxCost: "₹80",
            },
            {
              time: "10:00 AM",
              title: "Shri Kashi Vishwanath Dham Corridor",
              desc: "Darshan at the sacred Jyotirlinga followed by exploring the grand riverfront corridor.",
              placeSlug: "kashi-vishwanath-temple",
              approxCost: "Free",
            },
            {
              time: "02:00 PM",
              title: "Blue Lassi Break & Gali Exploration",
              desc: "Cool off with pomegranate and rabdi lassi in clay kullads.",
              placeSlug: "blue-lassi-shop",
              approxCost: "₹100",
            },
            {
              time: "05:45 PM",
              title: "Grand Ganga Aarti at Dashashwamedh",
              desc: "World-famous ritual of fire, conch shells, and evening brass lamps on the river.",
              placeSlug: "dashashwamedh-ghat",
              approxCost: "Free / ₹150 boat",
            },
            {
              time: "08:30 PM",
              title: "Dinner & Street Chaat Feast at Kashi Chaat Bhandar",
              desc: "World-famous Tamatar Chaat and Palak Patta chaat followed by hot Gulab Jamun.",
              placeSlug: "kashi-chaat-bhandar",
              approxCost: "₹150",
            },
          ],
        },
        {
          day: 2,
          title: "Fortresses, Sacred Shrines & Artisan Looms",
          theme: "Historical exploration, Southern Kashi temples, and master weavers",
          activities: [
            {
              time: "06:30 AM",
              title: "Historic Ghat Boat Row to Chet Singh Fort",
              desc: "Marvel at the 18th-century stone battlements from the water in morning light.",
              placeSlug: "chet-singh-ghat",
              approxCost: "₹200",
            },
            {
              time: "09:00 AM",
              title: "Sankat Mochan Hanuman Temple",
              desc: "Founded by Goswami Tulsidas. Enjoy divine peace and fresh Besan Ladoo prasad.",
              placeSlug: "sankat-mochan-hanuman-temple",
              approxCost: "Free",
            },
            {
              time: "11:30 AM",
              title: "Sarai Mohana Silk Weavers Colony",
              desc: "Watch master craftsmen hand-weave real gold zari Banarasi sarees on wooden looms.",
              placeSlug: "sarai-mohana-weaver-colony",
              approxCost: "Free",
            },
            {
              time: "04:30 PM",
              title: "Durga Kund & Lolark Kund Stepwell",
              desc: "18th-century red Nagara architecture and the mysterious 50-foot sun stepwell.",
              placeSlug: "durga-kund-temple",
              approxCost: "Free",
            },
            {
              time: "08:00 PM",
              title: "Banarasi Paan at Keshav Tambool",
              desc: "Melting Magahi leaf with rose gulkand and silver varq at Assi crossing.",
              placeSlug: "keshav-tambool-bhandar",
              approxCost: "₹40",
            },
          ],
        },
        {
          day: 3,
          title: "Hidden Lanes, Sacred Kotwal & Ancient Sarnath",
          theme: "Deep alleyways, guardian deity blessing, and peaceful Buddhist deer park",
          activities: [
            {
              time: "07:00 AM",
              title: "Winter Dewdrop Cloud Sweet: Malaiyo",
              desc: "Savor the frothed saffron milk dew foam at Chowk Neelkanth.",
              placeSlug: "shreeji-sweets-malaiyo",
              approxCost: "₹60",
            },
            {
              time: "09:00 AM",
              title: "Kaal Bhairav Temple Blessing",
              desc: "Seek the blessings of the Kotwal of Varanasi and receive the sacred black thread.",
              placeSlug: "kaal-bhairav-temple",
              approxCost: "Free",
            },
            {
              time: "11:30 AM",
              title: "Wandering Vishwanath Gali & Brass Market",
              desc: "Pick up hand-carved stone idols, genuine rudraksha, and brass lamps.",
              placeSlug: "vishwanath-gali-kachori-gali",
              approxCost: "₹300",
            },
            {
              time: "04:30 PM",
              title: "Manikarnika Ghat Contemplation",
              desc: "Experience life's profound truths at the timeless eternal fire from a quiet distance.",
              placeSlug: "manikarnika-ghat",
              approxCost: "Free",
            },
          ],
        },
      ]),
    },
  });

  console.log("✓ Seeded 3-Day Heritage & Soul itinerary");
  console.log("✅ Banaras Darshan seed completed successfully!");
}

main()
  .catch((e) => {
    console.error("Error seeding:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
